### PR TITLE
Fixed Reloading

### PR DESCRIPTION
**Pull request by NikhilKalloli**
Hey @KiranPolaki I encountered an issue. Whenever we press "again" the answer was same every time. I've fixed it and now it's working fine. Kindly review changes and merge this PR.

### CODE REVIEW

**Comment by KiranPolaki** [comment]
What do u mean by same! elaborate.

**Comment by NikhilKalloli** [comment]
> What do u mean by same! elaborate.

The answer that is SecreteNumber was being the same whenever "again" was pressed. I fixed it by enabling it to reload once it's pressed.

**Comment by NikhilKalloli** [comment]
> What do u mean by same! elaborate.

You can check it. First time you have to guess the number but the subsequent times it was the answer is the same number. To avoid it I just added an eventListener and it is working fine

**Comment by KiranPolaki** [comment]
Yes i see now!

**Pull request merged**
