### PR TITLE
Update newContributor.html

### PR DESCRIPTION
**Pull request by Anushreebasics**

### CODE REVIEW

**Comment by KiranPolaki** [comment]
Your contribution is added 🥳. work on another one now

**Comment by Anushreebasics** [comment]
but it is not showing in my hacktoberfest profile?

**Comment by KiranPolaki** [comment]
It will take some time!

**Comment by Anushreebasics** [comment]
ok thank you, I want to add a confetti when the user gives the correct answer how can I start?

**Comment by KiranPolaki** [comment]
That's a great idea 🤔🎊

to get started raise an issue before PR

and once that issue is assigned to u. u can start working on the index.html and once everything is done

Raise a Pull Request with proper screen shots of how it looks 📃.

That's it🥂

happy coding

**Pull request closed without merging**
