### PR TITLE
Added newContributor.html

### PR DESCRIPTION
**Pull request by NikhilKalloli**
I've added "newContributor.html" and maintained it's styling same as game. I've also fixed some typos in the "newContributor.html". I've added a new class in "styles.css" to place the Contributors button at the bottom. Please review the changes and merge this pull request. I would recommend to merge this before any other pull requests because if someone changes "newContributor.html" before this being merged, you'll have merge conflicts. And please add hacktoberfest tags for this PR. Have a nice Day:)

### CODE REVIEW

**Comment by KiranPolaki** [comment]
Hi Nikhil, I will review everything and let u know currently I am at work
and I don't have access to my personal laptop, so it will take some time.

**Comment by NikhilKalloli** [comment]
Yes, Sure. But I would recommend to merge this before any other pull requests.

**Comment by KiranPolaki** [comment]
Ya I know

**Comment by NikhilKalloli** [comment]
Screenshot 2023-10-26 201223

**Comment by KiranPolaki** [comment]
we can go with this for now we will make the enhancements later on by adding cards and everything :)
Great work

**Comment by KiranPolaki** [comment]
Hai make sure u are opening this in a blank page not in the same page!

**Comment by NikhilKalloli** [comment]
When u click on Contributors it open newContributor.html which is basically a new page. You can merge it.

**Comment by NikhilKalloli** [comment]
> we can go with this for now we will make the enhancements later on by adding cards and everything :)
> Great work 

Yeah I would like to work on that as well.

**Comment by NikhilKalloli** [comment]
Hey @KiranPolaki Can you please add hacktoberfest labels for this PR? And if there is something else to contribute then I'm up for it.

**Comment by NikhilKalloli** [comment]
Thanks a lot @KiranPolaki.

**Comment by KiranPolaki** [comment]
No need man i must thank you 😅Keep Hustling :)

**Pull request merged**
